version: '3'
services:
  rest-api:
    build: web-app/src/plRestApi
    ports:
      - "3000:3000"
      - "9230:9230"
    volumes:
      - "./web-app/src:/rest-api/src"
    depends_on: 
      - "db"
  spa:
    build: spa
    ports:
      - "4000:4000"
    volumes:
      - "./src:/singlepage/src/spa/frontend"
  web-app:
    build: web-app
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-app/src:/web-application/src"
    depends_on: 
      - "db"
  db:
    build: db
    ports: 
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=abc123"
      - "MYSQL_DATABASE=myDB"
  postgreDB:
    image: "postgres"
    container_name: "postgreDB"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=db"
      - "POSTGRES_USER=abc321"
      - "POSTGRES_PASSWORD=myPostgresDB"